.TH PRIMUSRUN "1" "February 2013" "primusrun"
.SH NAME
primusrun \- run an application on a discrete NVIDIA video card
.SH SYNOPSIS
\fBprimusrun\fR \fIcommand \fR
.SH DESCRIPTION
Primus is a shared library that provides OpenGL and GLX APIs and implements
low-overhead local-only client-side OpenGL offloading via GLX forking,
similar to VirtualGL. It intercepts GLX calls and redirects GL rendering
to a secondary X display, presumably driven by a faster GPU. On swapping
buffers, rendered contents are read back using a PBO and copied onto
the drawable it was supposed to be rendered on in the first place.
.sp
Primus is currently intended to be used alongside Bumblebee and provides a
drop-in replacement for optirun (i.e. "primusrun").
.SH VARIABLES
The following is a list of variables set by \fBprimusrun\fR which are
relevant for end users:
.IP "\s-1PRIMUS_SYNC\s0" 4
Readback-display synchronization method
.br
0: no sync, 1: D lags behind one frame, 2: fully synced
.IP "\s-1PRIMUS_VERBOSE\s0" 4
Verbosity level
.br
0: only errors, 1: warnings, 2: profiling
.IP "\s-1PRIMUS_DISPLAY\s0" 4
The secondary Xorg server display number
.IP "\s-1vblank_mode\s0" 4
Enable/disable vblank synchronisation
.br
0: sync on vblank disabled, 1: sync on vblank enabled
.SH EXAMPLES
.TP
\fBprimusrun glxgears \-info\fR
Runs the graphics demo supplied by mesa-utils to confirm whether the
discrete card is being used for GL rendering.
.TP
\fBPRIMUS_VERBOSE=2 primusrun glxgears\fR
Runs the graphics demo supplied by mesa-utils with verbose output from primus.
.TP
\fBvblank_mode=0 primusrun glxgears\fR
Disable vblank synchronisation, typically used for benchmarking purposes.
.SH ISSUES
Since compositing hurts performance, invoking primus when a compositing WM
is active is not recommended. If you need to use primus with compositing and
see flickering or bad performance, synchronizing primus' display thread with
the application's rendering thread may help.
.sp
\fBPRIMUS_SYNC=1 primusrun ...\fR
.sp
This makes primus display the previously rendered frame. Alternatively, with
PRIMUS_SYNC=2 primus will display the latest rendered frame, trading frame
rate for reduced visual latency.
.SH AUTHOR
Primus was created by Alexander Monakov <amonakov@gmail.com>.
.PP
This manual page was written by Vincent Cheng <Vincentc1208@gmail.com>,
for the Debian project (and may be used by others).
